backend:
  name: github
  repo: hitsujimaya/Sveltia-CMS-test
  branch: main

media_folder: "images"

collections:
  - name: "posts"
    label: "記事"
    folder: "_posts"
    create: true
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "本文", name: "body", widget: "markdown" }
